version: '3'
networks:
  deploy-guide-dev:
    driver: bridge
services:
  api:
    build:
      context: ./PizzaDeliveryApi
      dockerfile: Dockerfile
    ports:
      - 8080:80
    networks:
      - deploy-guide-dev
    depends_on:
      - database
  database:
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrongPassword
    ports:
      - 1433:1433
    networks:
      - deploy-guide-dev
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - deploy-guide-dev
  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.0
    ports:
      - 5601:5601
    networks:
      - deploy-guide-dev